---
project_name: helm-kubeconform
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/helm-kubeconform
    binary: ./bin/helm-kubeconform
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

archives:
  - id: tarball
    format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}"
    files:
      - LICENSE
      - plugin.yaml
