---
name: kubeconform
version: 0.1.0
usage: Validate Helm charts using Kubeconform
description: This plugin validates Helm charts using Kubeconform
ignoreFlags: false
command: $HELM_PLUGIN_DIR/bin/helm-kubeconform
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
